### ISSUE TITLE
Error while installing gitbook

### ISSUE THREAD

**Issue by rhaym-tech** [GitbookIO/gitbook-cli#125]
Hi, it looks like I can't install any version
```
rhaym@rhaym-debian # gitbook fetch 3.2.3 
Installing GitBook 3.2.3
\
Error: Failed to parse json
Unexpected token 'u' at 1:1
uleon.fumika@gmail.com"
^
```
any ideas, or atleast from which file is this error coming from

**Comment by rhaym-tech** [comment]
Here's debug version
```js
rhaym@rhaym-debian:# gitbook fetch 3.2.3 --debug
Installing GitBook 3.2.3
npm WARN deprecated chokidar@1.5.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated ignore@3.1.2: several bugs fixed in v3.2.1
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated request@2.72.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN optional dep failed, continuing fsevents@1.2.13
npm WARN deprecated highlight.js@9.2.0: Version no longer supported. Upgrade to @latest
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated asciidoctor.js@1.5.5-1: Package no longer supported. Replaced by @asciidoctor/core
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated har-validator@2.0.6: this library is no longer supported
npm WARN deprecated readdir-scoped-modules@1.1.0: This functionality has been moved to @npmcli/fs
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN optional dep failed, continuing fsevents@1.2.13
npm WARN deprecated datauri@0.2.1: Datauri 2.0 released. See more in https://github.com/data-uri/datauri/releases/tag/v2.0.0
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
\
> es5-ext@0.10.62 postinstall /tmp/tmp-13129Icf4ikRmJ0lq/node_modules/gitbook/node_modules/juice/node_modules/web-resource-inliner/node_modules/cli-color/node_modules/es5-ext
>  node -e "try{require('./_postinstall')}catch(e){}" || exit 0


Error: Failed to parse json
Unexpected token 'u' at 1:1
uleon.fumika@gmail.com"
^
Error: Failed to parse json
Unexpected token 'u' at 1:1
uleon.fumika@gmail.com"
^
    at parseError (/root/.nvm/versions/node/v18.16.0/lib/node_modules/gitbook-cli/node_modules/npmi/node_modules/npm/node_modules/read-package-json/read-json.js:390:11)
    at parseJson (/root/.nvm/versions/node/v18.16.0/lib/node_modules/gitbook-cli/node_modules/npmi/node_modules/npm/node_modules/read-package-json/read-json.js:79:23)
    at /root/.nvm/versions/node/v18.16.0/lib/node_modules/gitbook-cli/node_modules/npmi/node_modules/npm/node_modules/read-package-json/read-json.js:48:5
    at /root/.nvm/versions/node/v18.16.0/lib/node_modules/gitbook-cli/node_modules/npmi/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

```

**Comment by kenhys** [comment]
I'm not sure but it seems that fetched contributors metadata may be broken?

```
   (OMIT SOME DATA....)
    {
      "name": "Stefania Mellai",
      "email": "s.mellai@arduino.cc"
    },
    {
      "name": "Nebuleon Fumika",
      "email": "neb   },
    {
      "name": "John Foster",
      "email": "jfoster@esri.com"
    },
    {
      "name": "Robert Dodier",
      "email": "robert.dodier@gmail.com"
    },
    {
      "name": "Anthony Dugois",
      "email": "dev.anthonydugois@gmail.com"
    },
    {
      "name": "Qeole",
      "email": "qeole@outlook.com"
    },
    {
      "name": "Denis Ciccale",
      "email": "dciccale@gmail.com"
    },
    {
      "name": "Michael Johnston",
      "email": "lastobelus@gmail.com"
    },
    {
      "name": "Taras",
      "email": "oxdef@oxdef.info"
    }
  ],
  "bugs": {
    "url": "https://github.com/isagalaev/highlight.js/issues"
  },
  "license": "BSD-3-Clause",
```

**Comment by hprof** [comment]
same issue

**Comment by adam0x01** [comment]
Any update on this issue? Thanks🙏

**Comment by rhaym-tech** [comment]
This tool seems like it got discontinued and they moved to the web version
