### ISSUE TITLE
Error while installing gitbook

### ISSUE THREAD

**Issue by Mq-b** [GitbookIO/gitbook-cli#127]
C:\Users\A1387>npm install -g gitbook-cli

changed 46 packages in 9s

C:\Users\A1387>gitbook --version
CLI version: 2.3.2
Installing GitBook 3.2.3
C:\Users\A1387\AppData\Roaming\npm\node_modules\gitbook-cli\node_modules\npm\node_modules\graceful-fs\polyfills.js:287
      if (cb) cb.apply(this, arguments)
                 ^

TypeError: cb.apply is not a function
    at C:\Users\A1387\AppData\Roaming\npm\node_modules\gitbook-cli\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqCallback.oncomplete (node:fs:203:5)

Node.js v18.19.1

C:\Users\A1387>$ gitbook help
'$' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\A1387>gitbook help
Installing GitBook 3.2.3
C:\Users\A1387\AppData\Roaming\npm\node_modules\gitbook-cli\node_modules\npm\node_modules\graceful-fs\polyfills.js:287
      if (cb) cb.apply(this, arguments)
                 ^

TypeError: cb.apply is not a function
    at C:\Users\A1387\AppData\Roaming\npm\node_modules\gitbook-cli\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqCallback.oncomplete (node:fs:203:5)

Node.js v18.19.1

C:\Users\A1387>

**Comment by rhaym-tech** [comment]
downgrade to 12.18.2
