### ISSUE TITLE
Unable to install gitbook

### ISSUE THREAD

**Issue by greggigon** [GitbookIO/gitbook-cli#13]
Hi guys
Having a problem with **gitbook install**. Install process attempts to clone git repo over SSH however my Proxy only lets HTTP/HTTPS thorough. Would be nice to switch to HTTPS only cloning.

Error message bellow:

```shell
± |master ?:3 ✗| → gitbook -d install
Installing GitBook 2.4.3
-
Error: Command failed: git clone --template=/home/greg/.npm/_git-remotes/_templates --mirror git://github.com/anthonny/opal-npm-wrapper.git /home/greg/.npm/_git-remotes/git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3
Cloning into bare repository '/home/greg/.npm/_git-remotes/git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3'...
fatal: unable to connect to github.com:
github.com: Name or service not known


    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

```

Any workarounds or ideas ?
Greg

**Comment by FrenchBen** [comment]
what do you get if you do: `ssh -T git@github.com`

**Comment by greggigon** [comment]
Actually I managed to get it to work somehow, ages ago :)
Thanks Ben
