### ISSUE TITLE
gitbook update doesn't work

### ISSUE THREAD

**Issue by davis** [GitbookIO/gitbook-cli#21]
```
gitbook update
/usr/local/lib/node_modules/gitbook-cli/lib/index.js:71
    return local.current(null, {
                 ^

TypeError: local.current is not a function
    at Object.updateVersion [as update] (/usr/local/lib/node_modules/gitbook-cli/lib/index.js:71:18)
    at Command.<anonymous> (/usr/local/lib/node_modules/gitbook-cli/bin/gitbook.js:144:21)
    at Command.listener (/usr/local/lib/node_modules/gitbook-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:100:13)
    at Command.emit (events.js:185:7)
    at Command.parseArgs (/usr/local/lib/node_modules/gitbook-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/gitbook-cli/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/gitbook-cli/bin/gitbook.js:183:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

```
gitbook -V
2.0.1
```

**Comment by christian-posta** [comment]
I've got this on 2.1.1 also
