### ISSUE TITLE
specifying output dir breaks build

### ISSUE THREAD

**Issue by tomdavidson** [GitbookIO/gitbook-cli#46]
My build breaks when specifcying an output direcory:

```
$  gitbook build docs book
FileNotFoundError: No "README" file (or is ignored)

$:~/Projects/what-is-spa/what-is-spa.gitlab$ gitbook build
info: 12 plugins are installed 
info: 10 explicitly listed 
info: loading plugin "edit-link"... OK 
info: loading plugin "prism"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "include"... OK 
info: loading plugin "mermaid-gb3"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 2 pages 
info: found 1 asset files 
info: >> generation finished with success in 1.9s ! 

$ gitbook parse
info: Book located in: /home/... 
info: Configuration file is book.json 
info: Introduction file is index.md 
info: Table of Contents file is toc.md 
$ ~/...

$ gitbook --version
CLI version: 2.3.0
GitBook version: 3.2.0
```

**Comment by hawkchen** [comment]
I have the same issue when building in Jenkins

Extracted from the log:

> ...
> FileNotFoundError: No "README" file (or is ignored)[0m
> FileNotFoundError: No "README" file (or is ignored)
>     at new createError (/home/zkoss/.gitbook/versions/3.2.2/node_modules/error/typed.js:31:22)
>     at /home/zkoss/.gitbook/versions/3.2.2/lib/parse/parseReadme.js:18:19
>     at /home/zkoss/.gitbook/versions/3.2.2/node_modules/q/q.js:1229:26
>     at _fulfilled (/home/zkoss/.gitbook/versions/3.2.2/node_modules/q/q.js:834:54)
>     at self.promiseDispatch.done (/home/zkoss/.gitbook/versions/3.2.2/node_modules/q/q.js:863:30)
>     at Promise.promise.promiseDispatch (/home/zkoss/.gitbook/versions/3.2.2/node_modules/q/q.js:796:13)
>     at /home/zkoss/.gitbook/versions/3.2.2/node_modules/q/q.js:556:49
>     at runSingle (/home/zkoss/.gitbook/versions/3.2.2/node_modules/q/q.js:137:13)
>     at flush (/home/zkoss/.gitbook/versions/3.2.2/node_modules/q/q.js:125:13)
>     at _combinedTickCallback (internal/process/next_tick.js:73:7)
