### ISSUE TITLE
TypeError: Cannot read property 'commands' of null

### ISSUE THREAD

**Issue by kkmike999** [GitbookIO/gitbook-cli#77]
```
# npm -v
5.6.0

# gitbook --version
CLI version: 2.3.2
GitBook version: 3.2.3
```

When i exec `gitbook init` then:

```
Error loading version latest: /root/.gitbook/versions/3.2.3/node_modules/gitbook-markdown/node_modules/lodash/lodash.js:8018
    /**
    ^^^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)

TypeError: Cannot read property 'commands' of null
```

**Comment by mwolski89** [comment]
same here

**Comment by annu12340** [comment]
same here

**Comment by dorbodwolf** [comment]
same here

**Comment by flaced** [comment]
SAME HER

**Comment by xianglinhe** [comment]
I have the same issue, update nodejs to 12.12.0 solved my issue.
