### ISSUE TITLE
“gitbook init” error

### ISSUE THREAD

**Issue by kanglang** [GitbookIO/gitbook-cli#92]
$ gitbook -V
CLI version: 2.3.0
GitBook version: 3.2.3

$ gitbook init
Error loading version latest: Error: Cannot find module './ber/index'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Pactera\.gitbook\versions\3.2.3\node_modules\request\node_modul                                                                                                                              es\http-signature\node_modules\sshpk\node_modules\asn1\lib\index.js:6:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

TypeError: Cannot read property 'commands' of null

Q:
I don`t know what is happened! please help me !thank u..

**Comment by ddzy** [comment]
> $ gitbook -V
> CLI version: 2.3.0
> GitBook version: 3.2.3
> 
> $ gitbook init
> Error loading version latest: Error: Cannot find module './ber/index'
> at Function.Module._resolveFilename (module.js:547:15)
> at Function.Module._load (module.js:474:25)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)
> at Object. (C:\Users\Pactera.gitbook\versions\3.2.3\node_modules\request\node_modul es\http-signature\node_modules\sshpk\node_modules\asn1\lib\index.js:6:11)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)
> 
> TypeError: Cannot read property 'commands' of null
> 
> Q:
> I don`t know what is happened! please help me !thank u..

same problem.
